### ISSUE TITLE
Prepare test env

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/b2-deployment#2]
@tony-armstrong can you give a resource evaluation for deploying the rollup and b2 network?
@zhouop0 can you give a resource evaluation for testnet bitcoin client?
@thecookfrankie  can you give a resource evaluation for account abstraction bundle?

**Comment by tony-armstrong** [comment]
> @tony-armstrong can you give a resource evaluation for deploying the rollup and b2 network?

see [b2network/b2-internal-info](https://github.com/b2network/b2-internal-info)

**Comment by 0x677261706562616261** [comment]
@zhouop0 @thecookfrankie please add the info at [b2network/b2-internal-info](https://github.com/b2network/b2-internal-info)
